require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'banqi_assessment' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'banqi_assessmentTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
		installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'banqi_assessment-tvOS' do
  # Pods for banqi_assessment-tvOS

  target 'banqi_assessment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
